#### Load numpy

In [228]:
import numpy as np

#### The basics

#### One dimensional

In [229]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


#### Two dimensional

In [230]:
b = np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

#### Get the dimensions of the array

In [231]:
b.ndim

2

#### Shape of the array

In [232]:
b.shape # will output (2, 3) which means it has 2 rows and then 3 columns

(2, 3)

In [233]:
a.dtype

dtype('int64')

#### So by default the size of an array is 8 byte or int32. This is something we can change while defining the array

In [234]:
a = np.array([1, 4, 6], dtype = 'int32')


In [235]:
a.dtype

dtype('int32')

In [236]:
new_array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
new_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#### Get specific value

In [237]:
new_array[1, 3]

10

#### Get a specific row

In [238]:
new_array[0, :] # getting the first row

array([1, 2, 3, 4, 5, 6])

#### Get a specific column

In [239]:
new_array[ : , 1]

array([2, 8])

#### Let's do some fun activity
1. Import random 
2. Generate 2 numbers
4. Now use that to define the shape of the array
5. Get the size of the array
6. Generate those many numbers
7. Fill the dimensions with those numbers

In [240]:
import random
no_of_rows = random.randint(1000, 5349) # at least 1000 rows and can be upto 5349 for now
no_of_columns = random.randint(5, 20) # at least 5 columns and can be upto 20 for now
random_array = np.zeros((no_of_rows, no_of_columns), dtype=int)
random_array.shape


(3352, 6)

In [241]:
for i in range(no_of_rows):
    for j in range(no_of_columns):
        random_array[i][j] = random.randint(0, 1001)

In [242]:
random_array

array([[949, 190, 476, 500, 580, 999],
       [599, 105, 388, 803, 375, 618],
       [164,  57, 777, 785, 788, 340],
       ...,
       [970, 207, 345, 867, 985, 344],
       [379, 125, 312, 629,  71, 117],
       [213, 944,  87, 998, 529, 790]])

##### Now get a specific row

In [243]:
random_array[12, :] # we can verify if this is right by checking the no of columns

array([569, 428, 244, 432, 340, 158])

#### Get a specific column

In [246]:
if random_array.shape[1] >= 1:
    column_values = random_array[ : , random_array.shape[1] - 1] # getting the last column values
    print(f"It consists of {column_values.shape[0]} values")
    print(column_values)

It consists of 3352 values
[999 618 340 ... 344 117 790]


#### Getting a little fancy
#### [startindex : endindex : stepsize]