#### Load numpy

In [494]:
import numpy as np

#### The basics

#### One dimensional

In [495]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


#### Two dimensional

In [496]:
b = np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

#### Get the dimensions of the array

In [497]:
b.ndim

2

#### Shape of the array

In [498]:
b.shape # will output (2, 3) which means it has 2 rows and then 3 columns

(2, 3)

In [499]:
a.dtype

dtype('int64')

#### So by default the size of an array is 8 byte or int32. This is something we can change while defining the array

In [500]:
a = np.array([1, 4, 6], dtype = 'int32')


In [501]:
a.dtype

dtype('int32')

In [502]:
new_array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
new_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#### Get specific value

In [503]:
new_array[1, 3]

10

#### Get a specific row

In [504]:
new_array[0, :] # getting the first row

array([1, 2, 3, 4, 5, 6])

#### Get a specific column

In [505]:
new_array[ : , 1]

array([2, 8])

#### Let's do some fun activity
1. Import random 
2. Generate 2 numbers
4. Now use that to define the shape of the array
5. Get the size of the array
6. Generate those many numbers
7. Fill the dimensions with those numbers

In [506]:
import random
no_of_rows = random.randint(1000, 5349) # at least 1000 rows and can be upto 5349 for now
no_of_columns = random.randint(5, 20) # at least 5 columns and can be upto 20 for now
random_array = np.zeros((no_of_rows, no_of_columns), dtype=int)
random_array.shape


(3364, 5)

In [507]:
for i in range(no_of_rows):
    for j in range(no_of_columns):
        random_array[i][j] = random.randint(0, 1001)

In [508]:
random_array

array([[822, 820, 350, 461,  85],
       [466, 264,  90, 564, 237],
       [290, 617, 376, 130, 214],
       ...,
       [315, 423, 668, 652, 918],
       [955, 659, 809, 888, 975],
       [525, 957, 323, 199,  36]])

##### Now get a specific row

In [509]:
random_array[12, :] # we can verify if this is right by checking the no of columns

array([338, 737, 811, 578, 286])

#### Get a specific column

In [510]:
if random_array.shape[1] >= 1:
    column_values = random_array[ : , random_array.shape[1] - 1] # getting the last column values
    print(f"It consists of {column_values.shape[0]} values")
    print(column_values)

It consists of 3364 values
[ 85 237 214 ... 918 975  36]


#### Getting a little fancy
#### [startindex : endindex : stepsize]

In [511]:
# here 2 is the start index for the row and then 10 is the endindex which might be not available and then 2 stepsize means every other element
random_array[0, 2:10:2]

array([350,  85])

#### Changing the value at a particular index

In [512]:
random_array[1, 1] = 5

In [513]:
random_array[1, 1]

5

In [514]:
three_d_array = np.array([[[1, 2], [3, 4]], [[4, 16], [64, 34]]])
three_d_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 4, 16],
        [64, 34]]])

#### Accessing a 3d-element. Let's say if we want to access 64, then

In [515]:
three_d_array[1, 1, 0] # second array second row and then first column

64

In [516]:
three_d_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 4, 16],
        [64, 34]]])

#### Replacing values

In [517]:
three_d_array[ : , 1, :] = [[1, 2], [4,5]]

In [518]:
three_d_array

array([[[ 1,  2],
        [ 1,  2]],

       [[ 4, 16],
        [ 4,  5]]])

#### Initializing Different Types of Arrays

#### Initialising a 3-d array with zeros

In [519]:
np.zeros((2, 3, 2)) # 3-dimension initialiased with zeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

#### Initialising a 4-d array with ones

In [520]:
np.ones((2, 3, 2, 2)) # 4 dimensional

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

##### We can initialise it with any other number as well just need to use the full() function

In [521]:
np.full((3, 2, 3), 99)

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

#### Filling array with random values

In [522]:
new_random_array = np.random.randint(1, 100, size= (2, 3, 2)) # Generating a 3-dimension array with random numbers
new_random_array

array([[[32, 97],
        [44, 32],
        [76, 24]],

       [[46, 84],
        [ 5, 20],
        [87, 97]]])

#### Repeating a certain set of elements

In [523]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3, axis=0) # repeating the elements in the arr and 3 denotes the number of times we are repeating it
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [524]:
arr = np.array([[1, 2, 3]]) # this being 2-dimensional array unlike the first one
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### Identity Matrix

In [525]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### We want to create a array like this below
#### [1 1 1 1 1
####  1 0 0 0 1
####  1 0 9 0 1
####  1 0 0 0 1
####  1 1 1 1 1 ]

In [526]:
##### Logical interpretation
##### Initialize a matrix with all ones
##### Create another matrix with all zeros minus one row and column size
##### Add 9 or the element in the middle
##### and then replace this newly created matrix with the inner side of original matrix

In [527]:
original_array = np.ones((5, 5))
original_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [528]:
middle_with_zeros = np.zeros((3, 3))
middle_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [529]:
middle_with_zeros[1, 1] = 9
middle_with_zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [530]:
original_array[1:-1, 1:-1] = middle_with_zeros
original_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### NOTE : Please be careful while copying arrays

In [ ]:
a = np.array([1, 2, 3])
b = a # This will make b = a but also a = b and that's an issue
b[0] = 100
a # now a[0] will be set to 100

array([100,   2,   3])

#### Using copy function to avoid the above issue

In [539]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(f'a is {a}')
print(f'b is {b}')

a is [1 2 3]
b is [100   2   3]


### Mathematics

In [ ]:
a = np.array([1, 2 ,3 ,4])

array([3, 4, 5, 6])

In [543]:
a + 2

array([3, 4, 5, 6])

In [541]:
a - 2

array([-1,  0,  1,  2])

In [542]:
a  * 2

array([2, 4, 6, 8])

In [544]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [548]:
b = np.array([2, 4, 2, 4])
b

array([2, 4, 2, 4])

In [549]:
a + b

array([3, 6, 5, 8])

In [553]:
# Take trignometric values of the numbers\
print(np.sin(a))
print(np.cos(a))


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


##### Linear Algebra

In [554]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)

print(a)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [557]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [558]:
np.linalg.det(c) # Identity matrix has a determinant of 1

1.0

#### Statistics

In [560]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [561]:
stats.min()

1

In [562]:
stats.max()

6

In [566]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

#### Min and max according to vertical or horizontal axis represented by 0 or 1

In [564]:
stats.min(axis=0) # so basically among [1, 2, 3] and [4, 5, 6] the former is minimum

array([1, 2, 3])

In [565]:
stats.max(axis=1)

array([3, 6])

#### Reorganising arrays

#### Reshaping arrays.....
Arrays can be re-shaped based on the number of elements it contains.

In [574]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before.shape)

after = before.reshape(4,2)
print(after)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Stacking arrays vertically

In [576]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Stacking arrays horizontally

In [577]:
h1 = np.array([2, 3, 4, 3])
h2 = np.array([43, 35, 234, 33])

np.hstack([h1, h2, h2, h1, h1, h1])

array([  2,   3,   4,   3,  43,  35, 234,  33,  43,  35, 234,  33,   2,
         3,   4,   3,   2,   3,   4,   3,   2,   3,   4,   3])

### Miscellaneous
##### Load Data from file

In [579]:
data = np.genfromtxt('random_integers.txt', delimiter=' ')
data = data.astype('int32')
print(data)

[2605 2694 4970 3362 1878 9722 8219 4413 6959 3199 7015 9073  661 6881
 9460 8000 2361 6221 1286 9075 6742 7230  903 3209 6854  867 3550 8146
  548 2848 3298 9093 5727 1921 5747 5795 3764 3227 9076 8071 9612 3966
 8031 5172 8504 6078 1371 1449 4615 9296 3710 9435  474 2269 1513 4453
 6310 9906  593 6281 7970 7063 1322 3644 7689 6232 1749 8935 5016 5233
 7408 1155 4649 7750 5928 9623  238 6880 2058 9200 9928 2143 9503 4841
 8699 1178 2259 6973 4122 7623 3047 3489 6983 1410 5051 7617 8492 7610
 6179 5916 8805 1820 9308 8052 6485 4161 9748 8667 5295 2730 2483   41
 2136 5811 7527 5933  987  411 1298 1783 2122 9568 9853 5598 6002 2637
 9925 9030 1940 7611 3259 9453 8000 8665 4461 4558 5560 3657 5365 2064
 9129   26 3776 1225 2783 8585 6980 5117 9276 2266 1924 8892 8444 5598
 7710 5577 8237 9734  123 9129 4762 8092  690 8677 9815 6029 3422 1388
 9272 5962 9066 1059 6266 8332 3629 7749 9264 6383 7741 9599 7513 2578
 5846 3791 5413 9971  126 5952 1195 1236 7228 1998  578 5114 4432 3697
 7736 

In [587]:
data[data > 4593]

array([4970, 9722, 8219, 6959, 7015, 9073, 6881, 9460, 8000, 6221, 9075,
       6742, 7230, 6854, 8146, 9093, 5727, 5747, 5795, 9076, 8071, 9612,
       8031, 5172, 8504, 6078, 4615, 9296, 9435, 6310, 9906, 6281, 7970,
       7063, 7689, 6232, 8935, 5016, 5233, 7408, 4649, 7750, 5928, 9623,
       6880, 9200, 9928, 9503, 4841, 8699, 6973, 7623, 6983, 5051, 7617,
       8492, 7610, 6179, 5916, 8805, 9308, 8052, 6485, 9748, 8667, 5295,
       5811, 7527, 5933, 9568, 9853, 5598, 6002, 9925, 9030, 7611, 9453,
       8000, 8665, 5560, 5365, 9129, 8585, 6980, 5117, 9276, 8892, 8444,
       5598, 7710, 5577, 8237, 9734, 9129, 4762, 8092, 8677, 9815, 6029,
       9272, 5962, 9066, 6266, 8332, 7749, 9264, 6383, 7741, 9599, 7513,
       5846, 5413, 9971, 5952, 7228, 5114, 7736, 7015, 7660, 5368, 6022,
       6995, 4638, 8139, 9900, 9676, 6422, 6329, 9487, 7539, 4863, 8298,
       5266, 8423, 6150, 5018, 6425, 8088, 4814, 8943, 9588, 6786, 5522,
       5842, 5924, 5854, 9105, 6014, 8844, 9138, 46

In [589]:
np.any(data > 4593, axis=0)

True

In [592]:
data[((data > 4593) & (data < 5000))]

array([4970, 4615, 4649, 4841, 4762, 4638, 4863, 4814, 4624, 4760, 4808,
       4866, 4690, 4688, 4954, 4890, 4613, 4940, 4863, 4758, 4901, 4678,
       4771, 4905, 4765, 4771, 4928, 4621, 4649, 4741, 4622, 4618, 4729,
       4787], dtype=int32)

![Alt text](./get_the_rows_and_columns.png)

# How to get values from upper image
array[2:4, 0:2]
array[0:4, 1:-1]
array[[0, 4, 5], 3:]